### ISSUE TITLE
loss=NAN when training

### ISSUE THREAD

**Issue by Dou0405** [Skyy93/Sample4Geo#12]

**Comment by Dou0405** [comment]
Thanks for your nice work.
I'm trying to train vigor_cross but loss is nan from the beginning.I checked and found that the output features of model were NAN.
How can I fix that?

**Comment by mjc030225** [comment]
> Thanks for your nice work. I'm trying to train vigor_cross but loss is nan from the beginning.I checked and found that the output features of model were NAN. How can I fix that?

I faced the same situation. How do you resolve that problem?

**Comment by Skyy93** [comment]
@mjc030225 Did you changed anything in the code or use bf16 instead auf fp16?

**Comment by guoqiw** [comment]
> > Thanks for your nice work. I'm trying to train vigor_cross but loss is nan from the beginning.I checked and found that the output features of model were NAN. How can I fix that?
> 
> I faced the same situation. How do you resolve that problem?

I encountered the same problem. Have you solved it?
