### ISSUE TITLE
Are there any instructions?

### ISSUE THREAD

**Issue by GyoungTaeChae** [Skyy93/Sample4Geo#20]
Hello. Good to see your great works!

I wonder if there are any instructinos about packages,dependencies to be installed !

thankyou!

**Comment by Skyy93** [comment]
Yes, please install the packages mentioned in the requirements.txt
pip install -r requirements.txt

**Comment by GyoungTaeChae** [comment]
as beginner in github opensource , i missed that 😂 
i'll try it !
