### ISSUE TITLE
Training results on the university-1652 dataset

### ISSUE THREAD

**Issue by sugy0114** [Skyy93/Sample4Geo#32]
Thank you for your reply.
May I ask what weight file you are using for training? I used the weight file downloaded from Hugging Face, why is the final result AP value higher than the 91.39 mentioned in your paper?Here are my training results：
------------------------------[Epoch: 1]------------------------------
100%|████████████████████████████████████████████████████████████████████████| 295/295 [04:45<00:00,  1.03it/s, loss=0.8654, loss_avg=1.0052, lr=0.000000]
Epoch: 1, Train Loss = 1.005, Lr = 0.000000

------------------------------[Evaluate]------------------------------
Extract Features:
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.94it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 402/402 [01:43<00:00,  3.90it/s]
Compute Scores:
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 701/701 [00:03<00:00, 194.62it/s]
Recall@1: 95.0071 - Recall@5: 96.7190 - Recall@10: 97.1469 - Recall@top1: 99.2867 - AP: 91.6379

Shuffle Dataset:
42428it [00:00, 191806.88it/s]
Original Length: 37854 - Length after Shuffle: 37760
Break Counter: 512
Pairs left out of last batch to avoid creating noise: 94
First Element ID: 0945 - Last Element ID: 1646

**Comment by Skyy93** [comment]
[Answered](https://github.com/Skyy93/Sample4Geo/issues/33)
