### ISSUE TITLE
Training results on the university-1652 dataset

### ISSUE THREAD

**Issue by sugy0114** [Skyy93/Sample4Geo#33]
Thank you for your reply.
May I ask what weight file you are using for training? I used the weight file downloaded from Hugging Face, why is the final result AP value higher than the 91.39 mentioned in your paper?The following are the results of different weight files：
1.Model: convnext_base.fb_in22k_ft_in1k_384

{'input_size': (3, 224, 224), 'interpolation': 'bicubic', 'mean': (0.485, 0.456, 0.406), 'std': (0.229, 0.224, 0.225), 'crop_pct': 0.875, 'crop_mode': 'center'}
Start from: pretrained/university/convnext_base.fb_in22k_ft_in1k_384/weights_e1_0.9515.pth
GPUs available: 8

Image Size Query: (384, 384)
Image Size Ground: (384, 384)
Mean: (0.485, 0.456, 0.406)
Std:  (0.229, 0.224, 0.225)

Query Images Test: 701
Gallery Images Test: 51355

------------------------------[University-1652]------------------------------
Extract Features:
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:04<00:00,  1.43it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 402/402 [01:43<00:00,  3.87it/s]
Compute Scores:
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 701/701 [00:03<00:00, 193.97it/s]
Recall@1: 95.1498 - Recall@5: 97.0043 - Recall@10: 97.4322 - Recall@top1: 99.2867 - AP: 91.3901

2.Model: convnext_base.fb_in22k_ft_in1k_384

{'input_size': (3, 224, 224), 'interpolation': 'bicubic', 'mean': (0.485, 0.456, 0.406), 'std': (0.229, 0.224, 0.225), 'crop_pct': 0.875, 'crop_mode': 'center'}
Start from: /slurm-files/sgy/code/Sample4Geo/pretrained/university/convnext_base.fb_in22k_ft_in1k_384/weights_e1_0.9501.pth
GPUs available: 8

Image Size Query: (384, 384)
Image Size Ground: (384, 384)
Mean: (0.485, 0.456, 0.406)
Std:  (0.229, 0.224, 0.225)

Query Images Test: 701
Gallery Images Test: 51355

------------------------------[University-1652]------------------------------
Extract Features:
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:11<00:00,  2.00s/it]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 402/402 [03:41<00:00,  1.82it/s]
Compute Scores:
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 701/701 [00:06<00:00, 104.41it/s]
Recall@1: 95.0071 - Recall@5: 96.7190 - Recall@10: 97.1469 - Recall@top1: 99.2867 - AP: 91.6377

**Comment by Skyy93** [comment]
There might be some differences when using other hardware due to random seeds, but the difference here is marginal.
