### ISSUE TITLE
train_university.py setting's wrong? 

### ISSUE THREAD

**Issue by minuenergy** [Skyy93/Sample4Geo#35]
![image](https://github.com/user-attachments/assets/8fa17e30-5fd7-4ce0-9f90-5392420cf1a3)
I wonder why original training code setting for 1 epochs 
and when i try more than 1 epochs, model's performance getting lower and lower 

Could you provide the scratch training strategies ??

**Comment by Skyy93** [comment]
The 1 epoch is correct. Afterwards the performance deteriorates due to overfitting. If you want higher performance I can recommend using DINOv2 base/large as I did in my newer publications. 

https://dl.acm.org/doi/abs/10.1145/3689095.3689099
and
https://dl.acm.org/doi/abs/10.1145/3607834.3616567

**Comment by minuenergy** [comment]
ohhh I see 
thank you very much !!
