### ISSUE TITLE
how to train vigor?

### ISSUE THREAD

**Issue by xsf777** [Skyy93/Sample4Geo#37]
first,I run calc_distance_vigor.py,then I run train_vigor.py(python train_vigor.py),but find a error:
huggingface_hub.errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

**Comment by Skyy93** [comment]
Thank you for contacting us and for your interest in our research! It looks like your network is blocking access to the HuggingFace Hub. We download the weights for the ConvNext from [here] (https://huggingface.co/timm/convnext_base.fb_in22k_ft_in1k).  This is done using the timm library in model.py (create_model).

**Comment by xsf777** [comment]
How to download the model offline in https://huggingface.co/timm/convnext_base.fb_in22k_ft_in1k and then load it offline in model. py?

**Comment by Skyy93** [comment]
[Link](https://github.com/huggingface/pytorch-image-models/discussions/1826)

you can clone the repository on huggingface, on the right side there are 3 dots where when you click it a dropdown appears

**Comment by xsf777** [comment]
> [Link](https://github.com/huggingface/pytorch-image-models/discussions/1826)
> 
> you can clone the repository on huggingface, on the right side there are 3 dots where when you click it a dropdown appears

![image](https://github.com/user-attachments/assets/d8dce3cf-2b4a-407e-8e07-58ddec2d549e)
this?

**Comment by Skyy93** [comment]
https://huggingface.co/timm/convnext_base.fb_in22k_ft_in1k

**Comment by xsf777** [comment]
Due to network issues, I can only download the model offline. Which one should I download？
![image](https://github.com/user-attachments/assets/02a12e8a-f385-4be5-9a9b-283d03a3a26a)

**Comment by xsf777** [comment]
Can you give me CVACT dataset? Thanks!




路*/客
***@***.***



&nbsp;

**Comment by wincj** [comment]
> Can you give me CVACT dataset? Thanks!
> 
> 
> 
> 
> 路*/客
> ***@***.***
> 
> 
> 
> &nbsp;

Friend, have you obtained the datasets of CVACT and Vigor? Can you share it with me, if you have WeChat or other contact information
