### ISSUE TITLE
Results in CVACT_val.

### ISSUE THREAD

**Issue by liguopeng0923** [Skyy93/Sample4Geo#4]
Hi @Skyy93 ,

I want to report your ``Random" results of CVACT_val in my paper. But I cannot find that. Can you tell me?

Best,
Guopeng.

**Comment by Skyy93** [comment]
The scores for random were:
Recall@1: 87.4944 - Recall@5: 96.5669 - Recall@10: 97.5011 - Recall@top1: 98.9869

I will include them in an updated version of the Arxiv-Paper
